- name: Deploy Core AI Services and Applications
  hosts: controller_nodes[0]
  connection: local
  gather_facts: yes

  tags:
    - core-ai-services

  roles:
    - role: bootstrap_agent
      tags:
        - bootstrap_agent
    - role: term_everything
      tags:
        - term_everything
    - role: memory_service
      tags:
        - memory_service
    - role: pipecatapp
      tags:
        - pipecatapp
