- name: Deploy Core AI Services and Applications
  hosts: controller_nodes[0]
  connection: local
  gather_facts: yes

  vars_files:
    - "{{ playbook_dir }}/../../group_vars/all.yaml"
    - "{{ playbook_dir }}/../../group_vars/models.yaml"
    - "{{ playbook_dir }}/../../group_vars/external_experts.yaml"

  roles:
    - role: bootstrap_agent
    - role: term_everything
    - role: pipecatapp
