- name: Deploy Nomad
  hosts: all
  remote_user: "{{ target_user }}"
  become: yes

  tags:
    - nomad

  roles:
    - role: nomad
      tags:
        - nomad

  post_tasks:
    - name: Run Nomad Unit Tests
      ansible.builtin.command:
        cmd: "{{ ansible_playbook_python }} -m unittest tests.unit.test_infrastructure.TestInfrastructure.test_nomad_running"
        chdir: "{{ playbook_dir }}/../../"
      changed_when: false
      tags:
        - nomad_test
