- name: Create provisioning API directory
  file:
    path: "{{ provisioning_api_dir }}"
    state: directory
  become: yes
  when: inventory_hostname in groups['controller_nodes']

- name: Copy provisioning API script
  copy:
    src: provisioning_api.py
    dest: "{{ provisioning_api_dir }}/provisioning_api.py"
  become: yes
  when: inventory_hostname in groups['controller_nodes']

- name: Copy systemd service file
  template:
    src: provisioning-api.service.j2
    dest: /etc/systemd/system/provisioning-api.service
  notify: restart provisioning-api
  become: yes
  when: inventory_hostname in groups['controller_nodes']

- name: Allow Provisioning API port in UFW
  ansible.builtin.command: ufw allow {{ provisioning_api_port }}/tcp
  become: yes
  changed_when: false
  ignore_errors: yes
  when: inventory_hostname in groups['controller_nodes']

- name: Enable and start provisioning API service
  systemd:
    name: provisioning-api
    enabled: yes
    state: started
  become: yes
  when: inventory_hostname in groups['controller_nodes']
