---
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    tmpfs:
      - /run
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_python_interpreter: /usr/bin/python3
        target_user: root
  config_options:
    defaults:
      roles_path: "${MOLECULE_PROJECT_DIRECTORY}/.."
