- name: run nomad llamacpp-rpc job
  ansible.builtin.command:
    cmd: /usr/local/bin/nomad job run "{{ nomad_jobs_dir }}/llamacpp-rpc-{{ item.filename | regex_replace('\\.gguf$', '') }}.nomad"
  loop: "{{ all_models_for_rpc }}"
  environment:
    NOMAD_ADDR: "http://{{ cluster_ip }}:4646"
  loop_control:
    label: "{{ item.filename }}"
  become: yes

- name: update ld cache
  ansible.builtin.command:
    cmd: ldconfig
  become: yes
