- name: Create Postgres data directory
  file:
    path: "{{ nomad_volumes_dir }}/postgres_data"
    state: directory
    mode: '0755'
    owner: "999"
    group: "999"

- name: Create Postgres Nomad job file
  template:
    src: postgres.nomad.j2
    dest: "{{ nomad_jobs_dir }}/postgres.nomad"
  notify: Run Postgres job
