- name: Run moe-gateway job
  ansible.builtin.command:
    cmd: /usr/local/bin/nomad job run {{ nomad_jobs_dir }}/moe-gateway.nomad
  environment:
    NOMAD_ADDR: "http://{{ cluster_ip }}:{{ nomad_http_port }}"
  become: no
  changed_when: true
