- name: Restart Home Assistant
  ansible.builtin.command:
    cmd: nomad job run {{ nomad_jobs_dir }}/home-assistant.nomad
  environment:
    NOMAD_ADDR: "http://{{ ansible_facts['default_ipv4']['address'] }}:4646"
  changed_when: true
