- name: Restart Home Assistant
  ansible.builtin.command:
    cmd: nomad job run {{ nomad_jobs_dir }}/home-assistant.nomad
  environment:
    NOMAD_ADDR: "http://{{ cluster_ip }}:{{ nomad_http_port }}"
  changed_when: true
