- name: Restart Vision Job
  ansible.builtin.command:
    cmd: /usr/local/bin/nomad job run -detach {{ nomad_jobs_dir }}/vision.nomad
  environment:
    NOMAD_ADDR: "http://localhost:4646"
  changed_when: true
