- name: Common Setup
  hosts: all
  become: yes
  tasks:
    - name: Ensure the sudo package is installed
      tags:
        - sudo
      ansible.builtin.apt:
        name: sudo
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure the rsync package is installed
      tags:
        - rsync
      ansible.builtin.apt:
        name: rsync
        state: present

    - name: Ensure the sudo group exists
      tags:
        - sudo
      ansible.builtin.group:
        name: sudo
        state: present

    - name: Create the '{{ target_user }}' account with sudo access
      tags:
        - user
      ansible.builtin.user:
        name: "{{ target_user }}"
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Set correct permissions for the user's home directory
      tags:
        - user
      ansible.builtin.file:
        path: "/home/{{ target_user }}"
        state: directory
        mode: '0755'

    - name: Allow '{{ target_user }}' to have passwordless sudo access
      tags:
        - sudo
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/ansible-{{ target_user }}-nopasswd"
        line: "{{ target_user }} ALL=(ALL) NOPASSWD: ALL"
        create: yes
        validate: 'visudo -cf %s'
        mode: '0440'
