- name: Deploy pipecatapp for debugging
  hosts: all
  remote_user: "{{ target_user }}"
  become: yes

  vars_files:
    - "{{ playbook_dir }}/../../group_vars/all.yaml"
    - "{{ playbook_dir }}/../../group_vars/models.yaml"

  roles:
    - role: system_deps
    - role: python_deps
    - role: pipecatapp
