- hosts: pxe_server
  become: yes
  tasks:
    - name: Include Debian PXE role
      include_role:
        name: pxe_server
      when: pxe_os == 'debian'

    - name: Include NixOS PXE role
      include_role:
        name: nixos_pxe_server
      when: pxe_os == 'nixos'
