consul_version: "1.18.1"
consul_zip_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
consul_data_dir: "/opt/consul"
consul_config_dir: "/etc/consul.d"
consul_temp_cert_dir: "{{ ansible_user_dir }}/.consul_certs"
consul_datacenter: "dc1"
